name: ECS PR Deploy

on:
  workflow_dispatch:

jobs:
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Update AWS CLI version
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.13.5.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
