name: Terraform Lint

on:
  push:
    branches:
      - main

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Install tflint
        run: |
          curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r '.assets[].browser_download_url | select(contains("linux_amd64.zip"))')" -o tflint.zip
          unzip tflint.zip
          chmod +x tflint
          sudo mv tflint /usr/local/bin/
          
      - name: Format Terraform Code
        id: fmt
        run: terraform fmt -list=true -write=false -diff=true -check=true -recursive
        continue-on-error: false

      - name: Run Terraform Lint
        run: tflint --init && find . -type f -name "*.tf" -exec sh -c 'tflint -f compact {} >/dev/null 2>&1 || (tflint -f compact {})' \;
        continue-on-error: false 
    
