name: TF Lint and TF Sec

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  terraform-tflint-tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Format Terraform Code
        id: fmt
        run: terraform fmt -list=true -write=false -diff=true -check=true -recursive
#         continue-on-error: true

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.38.1

      - name: Run tflint
        run: tflint --init && find . -type f -name "*.tf" -exec sh -c 'tflint -f compact {} >/dev/null 2>&1 || (tflint -f compact {})' \;
        continue-on-error: false

      - name: Run tfsec PR commentor
        if: ${{ github.event_name == 'pull_request' }}
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tfsec_args: --force-all-dirs --no-module-downloads

      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.2
        with:
          version: v1.27.1
          additional_args: --exclude aws-s3-encryption-customer-key,aws-cloudwatch-log-group-customer-key --force-all-dirs --exclude-downloaded-modules
