name: Terraform Lint

on:
  push:
    branches:
      - main

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Install tflint
        run: |
          curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r '.assets[].browser_download_url | select(contains("linux_amd64.zip"))')" -o tflint.zip
          unzip tflint.zip
          chmod +x tflint
          sudo mv tflint /usr/local/bin/
          
      - name: some info
        run: ls && pwd 

      - name: Run Terraform Lint
        run: tflint --init && find . -type f -name "*.tf" -exec sh -c 'tflint -f compact {} >/dev/null 2>&1 || (tflint -f compact {})' \; || exit 1
      
      - name: Check tflint output for warnings and fail if found
        run: |
          if tflint --version | grep -q 'tflint version'; then
            tflint_output="$(tflint -f compact .)"
            if echo "$tflint_output" | grep -q "warning"; then
              echo "tflint warnings found:"
              echo "$tflint_output"
              exit 1
            fi
          fi
